name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B --no-transfer-progress package -P dist

    - name: Set version
      if: startsWith(github.ref, 'refs/tags/')
      env:
        REF: ${{ github.ref }}
      run: echo "VERSION=$(echo $REF | sed 's:refs/tags/v::' )" >> $GITHUB_ENV

    - name: Upload core distribution (tar.gz)
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: schunit-core/target/schunit-core-${VERSION}-dist.tar.gz
        label: SchUnit Core Library (tar.gz)

    - name: Upload core distribution (zip)
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: schunit-core/target/schunit-core-${VERSION}-dist.zip
        label: SchUnit Core Library (zip)
